//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass FuentesDeDatosModel
	/// La raíz en la cual los otros elementos son embebidos. Aparece como un diagrama.
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.FuentesDeDatosModel.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.FuentesDeDatosModel.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("4132a5b7-61bb-44af-ad84-23c8d95f3de9")]
	public partial class FuentesDeDatosModel : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// FuentesDeDatosModel domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x4132a5b7, 0x61bb, 0x44af, 0xad, 0x84, 0x23, 0xc8, 0xd9, 0x5f, 0x3d, 0xe9);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FuentesDeDatosModel(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FuentesDeDatosModel(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region FuentesDeDatos opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FuentesDeDatos.
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria> FuentesDeDatos
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria>, FuenteDeDatosPrimaria>(global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.FuentesDeDatosModelDomainRoleId);
			}
		}
		#endregion
		#region FormatosDeSalida opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FormatosDeSalida.
		/// Description for
		/// VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.FuentesDeDatosModel
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<TipoFormatoSalidaWeb> FormatosDeSalida
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<TipoFormatoSalidaWeb>, TipoFormatoSalidaWeb>(global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.FuentesDeDatosModelDomainRoleId);
			}
		}
		#endregion
		#region TiposDeChart opposite domain role accessor
		
		/// <summary>
		/// Gets a list of TiposDeChart.
		/// Description for
		/// VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.FuentesDeDatosModel
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<TipoDeChart> TiposDeChart
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<TipoDeChart>, TipoDeChart>(global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.FuentesDeDatosModelDomainRoleId);
			}
		}
		#endregion
		#region WebService opposite domain role accessor
		
		/// <summary>
		/// Gets a list of WebService.
		/// Description for
		/// VisorDatosDSL.FuentesDeDatosModelHasWebService.FuentesDeDatosModel
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<WebService> WebService
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<WebService>, WebService>(global::VisorDatosDSL.FuentesDeDatosModelHasWebService.FuentesDeDatosModelDomainRoleId);
			}
		}
		#endregion
		#region BaseDatos opposite domain role accessor
		
		/// <summary>
		/// Gets a list of BaseDatos.
		/// Description for
		/// VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.FuentesDeDatosModel
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<BaseDatos> BaseDatos
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<BaseDatos>, BaseDatos>(global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.FuentesDeDatosModelDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::VisorDatosDSL.FuenteDeDatosPrimaria.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::VisorDatosDSL.TipoFormatoSalidaWeb.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::VisorDatosDSL.TipoDeChart.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::VisorDatosDSL.WebService.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::VisorDatosDSL.BaseDatos.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::VisorDatosDSL.FuenteDeDatosPrimaria sourceFuenteDeDatosPrimaria1 = sourceElement as global::VisorDatosDSL.FuenteDeDatosPrimaria;
			if (sourceFuenteDeDatosPrimaria1 != null)
			{
				// Create link for path FuentesDeDatosModelHasFuentesDeDatos.FuentesDeDatos
				this.FuentesDeDatos.Add(sourceFuenteDeDatosPrimaria1);

				return;
			}
				
			global::VisorDatosDSL.TipoFormatoSalidaWeb sourceTipoFormatoSalidaWeb2 = sourceElement as global::VisorDatosDSL.TipoFormatoSalidaWeb;
			if (sourceTipoFormatoSalidaWeb2 != null)
			{
				// Create link for path FuentesDeDatosModelHasFormatosDeSalida.FormatosDeSalida
				this.FormatosDeSalida.Add(sourceTipoFormatoSalidaWeb2);

				return;
			}
				
			global::VisorDatosDSL.TipoDeChart sourceTipoDeChart3 = sourceElement as global::VisorDatosDSL.TipoDeChart;
			if (sourceTipoDeChart3 != null)
			{
				// Create link for path FuentesDeDatosModelHasTiposDeChart.TiposDeChart
				this.TiposDeChart.Add(sourceTipoDeChart3);

				return;
			}
				
			global::VisorDatosDSL.WebService sourceWebService4 = sourceElement as global::VisorDatosDSL.WebService;
			if (sourceWebService4 != null)
			{
				// Create link for path FuentesDeDatosModelHasWebService.WebService
				this.WebService.Add(sourceWebService4);

				return;
			}
				
			global::VisorDatosDSL.BaseDatos sourceBaseDatos5 = sourceElement as global::VisorDatosDSL.BaseDatos;
			if (sourceBaseDatos5 != null)
			{
				// Create link for path FuentesDeDatosModelHasBaseDatos.BaseDatos
				this.BaseDatos.Add(sourceBaseDatos5);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::VisorDatosDSL.FuenteDeDatosPrimaria sourceFuenteDeDatosPrimaria1 = sourceElement as global::VisorDatosDSL.FuenteDeDatosPrimaria;
			if (sourceFuenteDeDatosPrimaria1 != null)
			{
				// Delete link for path FuentesDeDatosModelHasFuentesDeDatos.FuentesDeDatos
				
				foreach (DslModeling::ElementLink link in global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.GetLinks((global::VisorDatosDSL.FuentesDeDatosModel)this, sourceFuenteDeDatosPrimaria1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.FuentesDeDatosModelDomainRoleId, global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.ElementDomainRoleId);
				}

				return;
			}
				
			global::VisorDatosDSL.TipoFormatoSalidaWeb sourceTipoFormatoSalidaWeb2 = sourceElement as global::VisorDatosDSL.TipoFormatoSalidaWeb;
			if (sourceTipoFormatoSalidaWeb2 != null)
			{
				// Delete link for path FuentesDeDatosModelHasFormatosDeSalida.FormatosDeSalida
				
				foreach (DslModeling::ElementLink link in global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.GetLinks((global::VisorDatosDSL.FuentesDeDatosModel)this, sourceTipoFormatoSalidaWeb2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.FuentesDeDatosModelDomainRoleId, global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId);
				}

				return;
			}
				
			global::VisorDatosDSL.TipoDeChart sourceTipoDeChart3 = sourceElement as global::VisorDatosDSL.TipoDeChart;
			if (sourceTipoDeChart3 != null)
			{
				// Delete link for path FuentesDeDatosModelHasTiposDeChart.TiposDeChart
				
				foreach (DslModeling::ElementLink link in global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.GetLinks((global::VisorDatosDSL.FuentesDeDatosModel)this, sourceTipoDeChart3))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.FuentesDeDatosModelDomainRoleId, global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.TipoDeChartDomainRoleId);
				}

				return;
			}
				
			global::VisorDatosDSL.WebService sourceWebService4 = sourceElement as global::VisorDatosDSL.WebService;
			if (sourceWebService4 != null)
			{
				// Delete link for path FuentesDeDatosModelHasWebService.WebService
				
				foreach (DslModeling::ElementLink link in global::VisorDatosDSL.FuentesDeDatosModelHasWebService.GetLinks((global::VisorDatosDSL.FuentesDeDatosModel)this, sourceWebService4))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::VisorDatosDSL.FuentesDeDatosModelHasWebService.FuentesDeDatosModelDomainRoleId, global::VisorDatosDSL.FuentesDeDatosModelHasWebService.WebServiceDomainRoleId);
				}

				return;
			}
				
			global::VisorDatosDSL.BaseDatos sourceBaseDatos5 = sourceElement as global::VisorDatosDSL.BaseDatos;
			if (sourceBaseDatos5 != null)
			{
				// Delete link for path FuentesDeDatosModelHasBaseDatos.BaseDatos
				
				foreach (DslModeling::ElementLink link in global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.GetLinks((global::VisorDatosDSL.FuentesDeDatosModel)this, sourceBaseDatos5))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.FuentesDeDatosModelDomainRoleId, global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.BaseDatosDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass FuenteDeDatosPrimaria
	/// Elements embedded in the model. Appear as boxes on the diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.FuenteDeDatosPrimaria.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.FuenteDeDatosPrimaria.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("7dc1c132-bab8-4288-ad7a-9ee3b421acc2")]
	public partial class FuenteDeDatosPrimaria : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// FuenteDeDatosPrimaria domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x7dc1c132, 0xbab8, 0x4288, 0xad, 0x7a, 0x9e, 0xe3, 0xb4, 0x21, 0xac, 0xc2);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FuenteDeDatosPrimaria(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FuenteDeDatosPrimaria(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0xcbe3c2ca, 0x5557, 0x4eb2, 0xbf, 0x14, 0xcb, 0x3b, 0xc3, 0x57, 0xe9, 0x6d);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Nombre Fuente de Datos";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Nombre de la Fuente de Datos
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.FuenteDeDatosPrimaria/Nombre.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.FuenteDeDatosPrimaria/Nombre.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Nombre Fuente de Datos")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("cbe3c2ca-5557-4eb2-bf14-cb3bc357e96d")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the FuenteDeDatosPrimaria.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<FuenteDeDatosPrimaria, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the FuenteDeDatosPrimaria.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the FuenteDeDatosPrimaria.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(FuenteDeDatosPrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(FuenteDeDatosPrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Ruta domain property code
		
		/// <summary>
		/// Ruta domain property Id.
		/// </summary>
		public static readonly global::System.Guid RutaDomainPropertyId = new global::System.Guid(0x4fae52e3, 0xec6d, 0x4cac, 0xb8, 0x60, 0x98, 0x46, 0x75, 0x8c, 0x37, 0x5c);
		
		/// <summary>
		/// Storage for Ruta
		/// </summary>
		private global::System.String rutaPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Ruta domain property.
		/// Description for VisorDatosDSL.FuenteDeDatosPrimaria.Ruta
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.FuenteDeDatosPrimaria/Ruta.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.FuenteDeDatosPrimaria/Ruta.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("4fae52e3-ec6d-4cac-b860-9846758c375c")]
		public global::System.String Ruta
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return rutaPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				RutaPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the FuenteDeDatosPrimaria.Ruta domain property.
		/// </summary>
		internal sealed partial class RutaPropertyHandler : DslModeling::DomainPropertyValueHandler<FuenteDeDatosPrimaria, global::System.String>
		{
			private RutaPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the FuenteDeDatosPrimaria.Ruta domain property value handler.
			/// </summary>
			public static readonly RutaPropertyHandler Instance = new RutaPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the FuenteDeDatosPrimaria.Ruta domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return RutaDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(FuenteDeDatosPrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.rutaPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(FuenteDeDatosPrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.rutaPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Metodo domain property code
		
		/// <summary>
		/// Metodo domain property Id.
		/// </summary>
		public static readonly global::System.Guid MetodoDomainPropertyId = new global::System.Guid(0x79f55435, 0xe7c3, 0x4d52, 0xa9, 0x61, 0x94, 0x81, 0x9a, 0xd6, 0x4a, 0xb0);
		
		/// <summary>
		/// Storage for Metodo
		/// </summary>
		private global::System.String metodoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Metodo domain property.
		/// Description for VisorDatosDSL.FuenteDeDatosPrimaria.Metodo
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.FuenteDeDatosPrimaria/Metodo.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.FuenteDeDatosPrimaria/Metodo.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("79f55435-e7c3-4d52-a961-94819ad64ab0")]
		public global::System.String Metodo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return metodoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				MetodoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the FuenteDeDatosPrimaria.Metodo domain property.
		/// </summary>
		internal sealed partial class MetodoPropertyHandler : DslModeling::DomainPropertyValueHandler<FuenteDeDatosPrimaria, global::System.String>
		{
			private MetodoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the FuenteDeDatosPrimaria.Metodo domain property value handler.
			/// </summary>
			public static readonly MetodoPropertyHandler Instance = new MetodoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the FuenteDeDatosPrimaria.Metodo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return MetodoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(FuenteDeDatosPrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.metodoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(FuenteDeDatosPrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.metodoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Descripcion domain property code
		
		/// <summary>
		/// Descripcion domain property Id.
		/// </summary>
		public static readonly global::System.Guid DescripcionDomainPropertyId = new global::System.Guid(0x0f8ebb92, 0x8a70, 0x4ad0, 0x9c, 0x35, 0x34, 0xd0, 0x04, 0x68, 0x2f, 0x1e);
		
		/// <summary>
		/// Storage for Descripcion
		/// </summary>
		private global::System.String descripcionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Descripcion domain property.
		/// Description for VisorDatosDSL.FuenteDeDatosPrimaria.Descripcion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.FuenteDeDatosPrimaria/Descripcion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.FuenteDeDatosPrimaria/Descripcion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("0f8ebb92-8a70-4ad0-9c35-34d004682f1e")]
		public global::System.String Descripcion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return descripcionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DescripcionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the FuenteDeDatosPrimaria.Descripcion domain property.
		/// </summary>
		internal sealed partial class DescripcionPropertyHandler : DslModeling::DomainPropertyValueHandler<FuenteDeDatosPrimaria, global::System.String>
		{
			private DescripcionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the FuenteDeDatosPrimaria.Descripcion domain property value handler.
			/// </summary>
			public static readonly DescripcionPropertyHandler Instance = new DescripcionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the FuenteDeDatosPrimaria.Descripcion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DescripcionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(FuenteDeDatosPrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.descripcionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(FuenteDeDatosPrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.descripcionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FuentesDeDatosModel opposite domain role accessor
		/// <summary>
		/// Gets or sets FuentesDeDatosModel.
		/// </summary>
		public virtual FuentesDeDatosModel FuentesDeDatosModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.ElementDomainRoleId) as FuentesDeDatosModel;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.ElementDomainRoleId, value);
			}
		}
		#endregion
		#region FormatosDeSalida opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FormatosDeSalida.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesFormatosDeSalida.FuenteDeDatosPrimaria
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<TipoFormatoSalidaWeb> FormatosDeSalida
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<TipoFormatoSalidaWeb>, TipoFormatoSalidaWeb>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesFormatosDeSalida.FuenteDeDatosPrimariaDomainRoleId);
			}
		}
		#endregion
		#region TiposDeChart opposite domain role accessor
		
		/// <summary>
		/// Gets a list of TiposDeChart.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesTiposDeChart.FuenteDeDatosPrimaria
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<TipoDeChart> TiposDeChart
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<TipoDeChart>, TipoDeChart>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesTiposDeChart.FuenteDeDatosPrimariaDomainRoleId);
			}
		}
		#endregion
		#region WebService opposite domain role accessor
		
		/// <summary>
		/// Gets a list of WebService.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesWebService.FuenteDeDatosPrimaria
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<WebService> WebService
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<WebService>, WebService>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesWebService.FuenteDeDatosPrimariaDomainRoleId);
			}
		}
		#endregion
		#region BaseDatos opposite domain role accessor
		
		/// <summary>
		/// Gets a list of BaseDatos.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesBaseDatos.FuenteDeDatosPrimaria
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<BaseDatos> BaseDatos
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<BaseDatos>, BaseDatos>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesBaseDatos.FuenteDeDatosPrimariaDomainRoleId);
			}
		}
		#endregion
	}
}
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass TipoFormatoSalidaWeb
	/// Description for VisorDatosDSL.TipoFormatoSalidaWeb
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.TipoFormatoSalidaWeb.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.TipoFormatoSalidaWeb.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("093fe7b6-e2e5-4dce-8f2b-242263383de3")]
	public partial class TipoFormatoSalidaWeb : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// TipoFormatoSalidaWeb domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x093fe7b6, 0xe2e5, 0x4dce, 0x8f, 0x2b, 0x24, 0x22, 0x63, 0x38, 0x3d, 0xe3);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TipoFormatoSalidaWeb(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TipoFormatoSalidaWeb(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0x596fef7f, 0x3bc6, 0x47c3, 0x88, 0x38, 0x27, 0x57, 0x3f, 0x73, 0x28, 0xdb);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Nombre Formato de Salida";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Nombre del Formato de Salida
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.TipoFormatoSalidaWeb/Nombre.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.TipoFormatoSalidaWeb/Nombre.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Nombre Formato de Salida")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("596fef7f-3bc6-47c3-8838-27573f7328db")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the TipoFormatoSalidaWeb.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<TipoFormatoSalidaWeb, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the TipoFormatoSalidaWeb.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the TipoFormatoSalidaWeb.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(TipoFormatoSalidaWeb element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(TipoFormatoSalidaWeb element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Descripcion domain property code
		
		/// <summary>
		/// Descripcion domain property Id.
		/// </summary>
		public static readonly global::System.Guid DescripcionDomainPropertyId = new global::System.Guid(0x29f36f49, 0xc908, 0x4af9, 0x9e, 0xc9, 0xf7, 0x68, 0x53, 0x34, 0xd3, 0xda);
		
		/// <summary>
		/// Storage for Descripcion
		/// </summary>
		private global::System.String descripcionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Descripcion domain property.
		/// Description for VisorDatosDSL.TipoFormatoSalidaWeb.Descripcion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.TipoFormatoSalidaWeb/Descripcion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.TipoFormatoSalidaWeb/Descripcion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("29f36f49-c908-4af9-9ec9-f7685334d3da")]
		public global::System.String Descripcion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return descripcionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DescripcionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the TipoFormatoSalidaWeb.Descripcion domain property.
		/// </summary>
		internal sealed partial class DescripcionPropertyHandler : DslModeling::DomainPropertyValueHandler<TipoFormatoSalidaWeb, global::System.String>
		{
			private DescripcionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the TipoFormatoSalidaWeb.Descripcion domain property value handler.
			/// </summary>
			public static readonly DescripcionPropertyHandler Instance = new DescripcionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the TipoFormatoSalidaWeb.Descripcion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DescripcionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(TipoFormatoSalidaWeb element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.descripcionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(TipoFormatoSalidaWeb element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.descripcionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FuentesDeDatosModel opposite domain role accessor
		/// <summary>
		/// Gets or sets FuentesDeDatosModel.
		/// Description for
		/// VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWeb
		/// </summary>
		public virtual FuentesDeDatosModel FuentesDeDatosModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId) as FuentesDeDatosModel;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId, value);
			}
		}
		#endregion
		#region FuenteDeDatosPrimaria opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FuenteDeDatosPrimaria.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesFormatosDeSalida.TipoFormatoSalidaWeb
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria> FuenteDeDatosPrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria>, FuenteDeDatosPrimaria>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId);
			}
		}
		#endregion
	}
}
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass TipoDeChart
	/// Description for VisorDatosDSL.TipoDeChart
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.TipoDeChart.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.TipoDeChart.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("6c78137a-66e1-4baa-9b71-b91814f5526e")]
	public partial class TipoDeChart : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// TipoDeChart domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6c78137a, 0x66e1, 0x4baa, 0x9b, 0x71, 0xb9, 0x18, 0x14, 0xf5, 0x52, 0x6e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TipoDeChart(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TipoDeChart(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0x2157f1b2, 0x3ffc, 0x475e, 0xb5, 0xd8, 0xed, 0xef, 0xf6, 0x78, 0x81, 0xd4);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Nombre Tipo de Chart";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Nombre del Tipo de Chart
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.TipoDeChart/Nombre.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.TipoDeChart/Nombre.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Nombre Tipo de Chart")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("2157f1b2-3ffc-475e-b5d8-edeff67881d4")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the TipoDeChart.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<TipoDeChart, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the TipoDeChart.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the TipoDeChart.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(TipoDeChart element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(TipoDeChart element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Descripcion domain property code
		
		/// <summary>
		/// Descripcion domain property Id.
		/// </summary>
		public static readonly global::System.Guid DescripcionDomainPropertyId = new global::System.Guid(0x21c9395d, 0x1d7d, 0x4395, 0xa1, 0x31, 0xcd, 0x59, 0x06, 0xbe, 0x93, 0x06);
		
		/// <summary>
		/// Storage for Descripcion
		/// </summary>
		private global::System.String descripcionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Descripcion domain property.
		/// Description for VisorDatosDSL.TipoDeChart.Descripcion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.TipoDeChart/Descripcion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.TipoDeChart/Descripcion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("21c9395d-1d7d-4395-a131-cd5906be9306")]
		public global::System.String Descripcion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return descripcionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DescripcionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the TipoDeChart.Descripcion domain property.
		/// </summary>
		internal sealed partial class DescripcionPropertyHandler : DslModeling::DomainPropertyValueHandler<TipoDeChart, global::System.String>
		{
			private DescripcionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the TipoDeChart.Descripcion domain property value handler.
			/// </summary>
			public static readonly DescripcionPropertyHandler Instance = new DescripcionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the TipoDeChart.Descripcion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DescripcionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(TipoDeChart element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.descripcionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(TipoDeChart element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.descripcionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FuentesDeDatosModel opposite domain role accessor
		/// <summary>
		/// Gets or sets FuentesDeDatosModel.
		/// Description for VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.TipoDeChart
		/// </summary>
		public virtual FuentesDeDatosModel FuentesDeDatosModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.TipoDeChartDomainRoleId) as FuentesDeDatosModel;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.TipoDeChartDomainRoleId, value);
			}
		}
		#endregion
		#region FuenteDeDatosPrimaria opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FuenteDeDatosPrimaria.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesTiposDeChart.TipoDeChart
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria> FuenteDeDatosPrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria>, FuenteDeDatosPrimaria>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesTiposDeChart.TipoDeChartDomainRoleId);
			}
		}
		#endregion
	}
}
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass WebService
	/// Description for VisorDatosDSL.WebService
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.WebService.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.WebService.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("6991977d-8349-461a-a6a2-0a2b7ee94baf")]
	public partial class WebService : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// WebService domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6991977d, 0x8349, 0x461a, 0xa6, 0xa2, 0x0a, 0x2b, 0x7e, 0xe9, 0x4b, 0xaf);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WebService(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WebService(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0xfce901b2, 0x67a3, 0x4598, 0xa1, 0x10, 0x8c, 0xe5, 0xab, 0x76, 0x71, 0xc5);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Web Service";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Description for VisorDatosDSL.WebService.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.WebService/Nombre.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.WebService/Nombre.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Web Service")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("fce901b2-67a3-4598-a110-8ce5ab7671c5")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WebService.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<WebService, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WebService.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WebService.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WebService element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WebService element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Descripcion domain property code
		
		/// <summary>
		/// Descripcion domain property Id.
		/// </summary>
		public static readonly global::System.Guid DescripcionDomainPropertyId = new global::System.Guid(0x2c80a27a, 0x0eb6, 0x4a83, 0xb5, 0x20, 0x23, 0xc3, 0x4a, 0x1c, 0xb1, 0x21);
		
		/// <summary>
		/// Storage for Descripcion
		/// </summary>
		private global::System.String descripcionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Descripcion domain property.
		/// Description for VisorDatosDSL.WebService.Descripcion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.WebService/Descripcion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.WebService/Descripcion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("2c80a27a-0eb6-4a83-b520-23c34a1cb121")]
		public global::System.String Descripcion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return descripcionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DescripcionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WebService.Descripcion domain property.
		/// </summary>
		internal sealed partial class DescripcionPropertyHandler : DslModeling::DomainPropertyValueHandler<WebService, global::System.String>
		{
			private DescripcionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WebService.Descripcion domain property value handler.
			/// </summary>
			public static readonly DescripcionPropertyHandler Instance = new DescripcionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WebService.Descripcion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DescripcionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WebService element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.descripcionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WebService element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.descripcionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Ruta domain property code
		
		/// <summary>
		/// Ruta domain property Id.
		/// </summary>
		public static readonly global::System.Guid RutaDomainPropertyId = new global::System.Guid(0x7229c1b9, 0xc5e9, 0x437a, 0xb2, 0x13, 0x71, 0x5b, 0xaf, 0xd8, 0x36, 0x6e);
		
		/// <summary>
		/// Storage for Ruta
		/// </summary>
		private global::System.String rutaPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Ruta domain property.
		/// Description for VisorDatosDSL.WebService.Ruta
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.WebService/Ruta.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.WebService/Ruta.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("7229c1b9-c5e9-437a-b213-715bafd8366e")]
		public global::System.String Ruta
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return rutaPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				RutaPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WebService.Ruta domain property.
		/// </summary>
		internal sealed partial class RutaPropertyHandler : DslModeling::DomainPropertyValueHandler<WebService, global::System.String>
		{
			private RutaPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WebService.Ruta domain property value handler.
			/// </summary>
			public static readonly RutaPropertyHandler Instance = new RutaPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WebService.Ruta domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return RutaDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WebService element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.rutaPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WebService element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.rutaPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FuenteDeDatosPrimaria opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FuenteDeDatosPrimaria.
		/// Description for
		/// VisorDatosDSL.FuenteDeDatosPrimariaReferencesWebService.WebService
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria> FuenteDeDatosPrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria>, FuenteDeDatosPrimaria>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesWebService.WebServiceDomainRoleId);
			}
		}
		#endregion
		#region FuentesDeDatosModel opposite domain role accessor
		/// <summary>
		/// Gets or sets FuentesDeDatosModel.
		/// Description for VisorDatosDSL.FuentesDeDatosModelHasWebService.WebService
		/// </summary>
		public virtual FuentesDeDatosModel FuentesDeDatosModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasWebService.WebServiceDomainRoleId) as FuentesDeDatosModel;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasWebService.WebServiceDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainClass BaseDatos
	/// Description for VisorDatosDSL.BaseDatos
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.BaseDatos.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.BaseDatos.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("2e5a4d5e-b640-4a1b-8ce4-ec18a7008ceb")]
	public partial class BaseDatos : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// BaseDatos domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2e5a4d5e, 0xb640, 0x4a1b, 0x8c, 0xe4, 0xec, 0x18, 0xa7, 0x00, 0x8c, 0xeb);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public BaseDatos(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public BaseDatos(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Nombre domain property code
		
		/// <summary>
		/// Nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid NombreDomainPropertyId = new global::System.Guid(0x08bc773e, 0x4abc, 0x4272, 0xa4, 0x93, 0xc8, 0xa5, 0x01, 0x5b, 0x17, 0x3e);
		
		/// <summary>
		/// Storage for Nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = "Base de Datos";
		
		/// <summary>
		/// Gets or sets the value of Nombre domain property.
		/// Description for VisorDatosDSL.BaseDatos.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.BaseDatos/Nombre.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.BaseDatos/Nombre.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Base de Datos")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("08bc773e-4abc-4272-a493-c8a5015b173e")]
		public global::System.String Nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the BaseDatos.Nombre domain property.
		/// </summary>
		internal sealed partial class NombrePropertyHandler : DslModeling::DomainPropertyValueHandler<BaseDatos, global::System.String>
		{
			private NombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the BaseDatos.Nombre domain property value handler.
			/// </summary>
			public static readonly NombrePropertyHandler Instance = new NombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the BaseDatos.Nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(BaseDatos element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(BaseDatos element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Descripcion domain property code
		
		/// <summary>
		/// Descripcion domain property Id.
		/// </summary>
		public static readonly global::System.Guid DescripcionDomainPropertyId = new global::System.Guid(0x1d4c9496, 0x5075, 0x46aa, 0x8a, 0x96, 0x4c, 0x3e, 0x44, 0x4d, 0x76, 0x24);
		
		/// <summary>
		/// Storage for Descripcion
		/// </summary>
		private global::System.String descripcionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Descripcion domain property.
		/// Description for VisorDatosDSL.BaseDatos.Descripcion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.BaseDatos/Descripcion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.BaseDatos/Descripcion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("1d4c9496-5075-46aa-8a96-4c3e444d7624")]
		public global::System.String Descripcion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return descripcionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DescripcionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the BaseDatos.Descripcion domain property.
		/// </summary>
		internal sealed partial class DescripcionPropertyHandler : DslModeling::DomainPropertyValueHandler<BaseDatos, global::System.String>
		{
			private DescripcionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the BaseDatos.Descripcion domain property value handler.
			/// </summary>
			public static readonly DescripcionPropertyHandler Instance = new DescripcionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the BaseDatos.Descripcion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DescripcionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(BaseDatos element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.descripcionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(BaseDatos element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.descripcionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region CadenaConexion domain property code
		
		/// <summary>
		/// CadenaConexion domain property Id.
		/// </summary>
		public static readonly global::System.Guid CadenaConexionDomainPropertyId = new global::System.Guid(0x8cdeb6c4, 0x9204, 0x43e2, 0x98, 0x84, 0x09, 0xb6, 0xcf, 0xaf, 0xad, 0x3c);
		
		/// <summary>
		/// Storage for CadenaConexion
		/// </summary>
		private global::System.String cadenaConexionPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of CadenaConexion domain property.
		/// Description for VisorDatosDSL.BaseDatos.Cadena Conexion
		/// </summary>
		[DslDesign::DisplayNameResource("VisorDatosDSL.BaseDatos/CadenaConexion.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("VisorDatosDSL.BaseDatos/CadenaConexion.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("8cdeb6c4-9204-43e2-9884-09b6cfafad3c")]
		public global::System.String CadenaConexion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cadenaConexionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				CadenaConexionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the BaseDatos.CadenaConexion domain property.
		/// </summary>
		internal sealed partial class CadenaConexionPropertyHandler : DslModeling::DomainPropertyValueHandler<BaseDatos, global::System.String>
		{
			private CadenaConexionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the BaseDatos.CadenaConexion domain property value handler.
			/// </summary>
			public static readonly CadenaConexionPropertyHandler Instance = new CadenaConexionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the BaseDatos.CadenaConexion domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return CadenaConexionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(BaseDatos element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cadenaConexionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(BaseDatos element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cadenaConexionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FuentesDeDatosModel opposite domain role accessor
		/// <summary>
		/// Gets or sets FuentesDeDatosModel.
		/// Description for VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.BaseDatos
		/// </summary>
		public virtual FuentesDeDatosModel FuentesDeDatosModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.BaseDatosDomainRoleId) as FuentesDeDatosModel;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.BaseDatosDomainRoleId, value);
			}
		}
		#endregion
		#region FuenteDeDatosPrimaria opposite domain role accessor
		
		/// <summary>
		/// Gets a list of FuenteDeDatosPrimaria.
		/// Description for VisorDatosDSL.FuenteDeDatosPrimariaReferencesBaseDatos.BaseDatos
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria> FuenteDeDatosPrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<FuenteDeDatosPrimaria>, FuenteDeDatosPrimaria>(global::VisorDatosDSL.FuenteDeDatosPrimariaReferencesBaseDatos.BaseDatosDomainRoleId);
			}
		}
		#endregion
	}
}
