//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace VisorDatosDSL
{
	/// <summary>
	/// DomainModel VisorDatosDSLDomainModel
	/// Description for VisorDatosDSL.VisorDatosDSL
	/// </summary>
	[DslDesign::DisplayNameResource("VisorDatosDSL.VisorDatosDSLDomainModel.DisplayName", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisorDatosDSL.VisorDatosDSLDomainModel.Description", typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel), "VisorDatosDSL.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("cfecef4d-5a72-4b3e-8b4c-8e93d4176ef1")]
	public partial class VisorDatosDSLDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// VisorDatosDSLDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xcfecef4d, 0x5a72, 0x4b3e, 0x8b, 0x4c, 0x8e, 0x93, 0xd4, 0x17, 0x6e, 0xf1);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public VisorDatosDSLDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(FuentesDeDatosModel),
				typeof(FuenteDeDatosPrimaria),
				typeof(TipoFormatoSalidaWeb),
				typeof(TipoDeChart),
				typeof(WebService),
				typeof(BaseDatos),
				typeof(FuentesDeDatosModelHasFuentesDeDatos),
				typeof(FuentesDeDatosModelHasFormatosDeSalida),
				typeof(FuentesDeDatosModelHasTiposDeChart),
				typeof(FuenteDeDatosPrimariaReferencesFormatosDeSalida),
				typeof(FuenteDeDatosPrimariaReferencesTiposDeChart),
				typeof(FuenteDeDatosPrimariaReferencesWebService),
				typeof(FuentesDeDatosModelHasWebService),
				typeof(FuentesDeDatosModelHasBaseDatos),
				typeof(FuenteDeDatosPrimariaReferencesBaseDatos),
				typeof(VisorDatosDSLDiagram),
				typeof(ConectorFuente_FormatoSalida),
				typeof(ConectorFuente_TipoChart),
				typeof(ConectorFuente_WebService),
				typeof(ConectorFuente_BaseDatos),
				typeof(FuenteDeDatosShape),
				typeof(FormatoDeSalidaShape),
				typeof(TipoDeChartShape),
				typeof(WebServiceShape),
				typeof(BaseDatosShape),
				typeof(global::VisorDatosDSL.FixUpDiagram),
				typeof(global::VisorDatosDSL.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(FuenteDeDatosPrimaria), "Nombre", FuenteDeDatosPrimaria.NombreDomainPropertyId, typeof(FuenteDeDatosPrimaria.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(FuenteDeDatosPrimaria), "Ruta", FuenteDeDatosPrimaria.RutaDomainPropertyId, typeof(FuenteDeDatosPrimaria.RutaPropertyHandler)),
				new DomainMemberInfo(typeof(FuenteDeDatosPrimaria), "Metodo", FuenteDeDatosPrimaria.MetodoDomainPropertyId, typeof(FuenteDeDatosPrimaria.MetodoPropertyHandler)),
				new DomainMemberInfo(typeof(FuenteDeDatosPrimaria), "Descripcion", FuenteDeDatosPrimaria.DescripcionDomainPropertyId, typeof(FuenteDeDatosPrimaria.DescripcionPropertyHandler)),
				new DomainMemberInfo(typeof(TipoFormatoSalidaWeb), "Nombre", TipoFormatoSalidaWeb.NombreDomainPropertyId, typeof(TipoFormatoSalidaWeb.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(TipoFormatoSalidaWeb), "Descripcion", TipoFormatoSalidaWeb.DescripcionDomainPropertyId, typeof(TipoFormatoSalidaWeb.DescripcionPropertyHandler)),
				new DomainMemberInfo(typeof(TipoDeChart), "Nombre", TipoDeChart.NombreDomainPropertyId, typeof(TipoDeChart.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(TipoDeChart), "Descripcion", TipoDeChart.DescripcionDomainPropertyId, typeof(TipoDeChart.DescripcionPropertyHandler)),
				new DomainMemberInfo(typeof(WebService), "Nombre", WebService.NombreDomainPropertyId, typeof(WebService.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(WebService), "Descripcion", WebService.DescripcionDomainPropertyId, typeof(WebService.DescripcionPropertyHandler)),
				new DomainMemberInfo(typeof(WebService), "Ruta", WebService.RutaDomainPropertyId, typeof(WebService.RutaPropertyHandler)),
				new DomainMemberInfo(typeof(BaseDatos), "Nombre", BaseDatos.NombreDomainPropertyId, typeof(BaseDatos.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(BaseDatos), "Descripcion", BaseDatos.DescripcionDomainPropertyId, typeof(BaseDatos.DescripcionPropertyHandler)),
				new DomainMemberInfo(typeof(BaseDatos), "CadenaConexion", BaseDatos.CadenaConexionDomainPropertyId, typeof(BaseDatos.CadenaConexionPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasFuentesDeDatos), "FuentesDeDatosModel", FuentesDeDatosModelHasFuentesDeDatos.FuentesDeDatosModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasFuentesDeDatos), "Element", FuentesDeDatosModelHasFuentesDeDatos.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasFormatosDeSalida), "FuentesDeDatosModel", FuentesDeDatosModelHasFormatosDeSalida.FuentesDeDatosModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasFormatosDeSalida), "TipoFormatoSalidaWeb", FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasTiposDeChart), "FuentesDeDatosModel", FuentesDeDatosModelHasTiposDeChart.FuentesDeDatosModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasTiposDeChart), "TipoDeChart", FuentesDeDatosModelHasTiposDeChart.TipoDeChartDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesFormatosDeSalida), "FuenteDeDatosPrimaria", FuenteDeDatosPrimariaReferencesFormatosDeSalida.FuenteDeDatosPrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesFormatosDeSalida), "TipoFormatoSalidaWeb", FuenteDeDatosPrimariaReferencesFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesTiposDeChart), "FuenteDeDatosPrimaria", FuenteDeDatosPrimariaReferencesTiposDeChart.FuenteDeDatosPrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesTiposDeChart), "TipoDeChart", FuenteDeDatosPrimariaReferencesTiposDeChart.TipoDeChartDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesWebService), "FuenteDeDatosPrimaria", FuenteDeDatosPrimariaReferencesWebService.FuenteDeDatosPrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesWebService), "WebService", FuenteDeDatosPrimariaReferencesWebService.WebServiceDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasWebService), "FuentesDeDatosModel", FuentesDeDatosModelHasWebService.FuentesDeDatosModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasWebService), "WebService", FuentesDeDatosModelHasWebService.WebServiceDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasBaseDatos), "FuentesDeDatosModel", FuentesDeDatosModelHasBaseDatos.FuentesDeDatosModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuentesDeDatosModelHasBaseDatos), "BaseDatos", FuentesDeDatosModelHasBaseDatos.BaseDatosDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesBaseDatos), "FuenteDeDatosPrimaria", FuenteDeDatosPrimariaReferencesBaseDatos.FuenteDeDatosPrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(FuenteDeDatosPrimariaReferencesBaseDatos), "BaseDatos", FuenteDeDatosPrimariaReferencesBaseDatos.BaseDatosDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(16);
				createElementMap.Add(typeof(FuentesDeDatosModel), 0);
				createElementMap.Add(typeof(FuenteDeDatosPrimaria), 1);
				createElementMap.Add(typeof(TipoFormatoSalidaWeb), 2);
				createElementMap.Add(typeof(TipoDeChart), 3);
				createElementMap.Add(typeof(WebService), 4);
				createElementMap.Add(typeof(BaseDatos), 5);
				createElementMap.Add(typeof(VisorDatosDSLDiagram), 6);
				createElementMap.Add(typeof(ConectorFuente_FormatoSalida), 7);
				createElementMap.Add(typeof(ConectorFuente_TipoChart), 8);
				createElementMap.Add(typeof(ConectorFuente_WebService), 9);
				createElementMap.Add(typeof(ConectorFuente_BaseDatos), 10);
				createElementMap.Add(typeof(FuenteDeDatosShape), 11);
				createElementMap.Add(typeof(FormatoDeSalidaShape), 12);
				createElementMap.Add(typeof(TipoDeChartShape), 13);
				createElementMap.Add(typeof(WebServiceShape), 14);
				createElementMap.Add(typeof(BaseDatosShape), 15);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::VisorDatosDSL.VisorDatosDSLDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new FuentesDeDatosModel(partition, propertyAssignments);
				case 1: return new FuenteDeDatosPrimaria(partition, propertyAssignments);
				case 2: return new TipoFormatoSalidaWeb(partition, propertyAssignments);
				case 3: return new TipoDeChart(partition, propertyAssignments);
				case 4: return new WebService(partition, propertyAssignments);
				case 5: return new BaseDatos(partition, propertyAssignments);
				case 6: return new VisorDatosDSLDiagram(partition, propertyAssignments);
				case 7: return new ConectorFuente_FormatoSalida(partition, propertyAssignments);
				case 8: return new ConectorFuente_TipoChart(partition, propertyAssignments);
				case 9: return new ConectorFuente_WebService(partition, propertyAssignments);
				case 10: return new ConectorFuente_BaseDatos(partition, propertyAssignments);
				case 11: return new FuenteDeDatosShape(partition, propertyAssignments);
				case 12: return new FormatoDeSalidaShape(partition, propertyAssignments);
				case 13: return new TipoDeChartShape(partition, propertyAssignments);
				case 14: return new WebServiceShape(partition, propertyAssignments);
				case 15: return new BaseDatosShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementLinkMap.Add(typeof(FuentesDeDatosModelHasFuentesDeDatos), 0);
				createElementLinkMap.Add(typeof(FuentesDeDatosModelHasFormatosDeSalida), 1);
				createElementLinkMap.Add(typeof(FuentesDeDatosModelHasTiposDeChart), 2);
				createElementLinkMap.Add(typeof(FuenteDeDatosPrimariaReferencesFormatosDeSalida), 3);
				createElementLinkMap.Add(typeof(FuenteDeDatosPrimariaReferencesTiposDeChart), 4);
				createElementLinkMap.Add(typeof(FuenteDeDatosPrimariaReferencesWebService), 5);
				createElementLinkMap.Add(typeof(FuentesDeDatosModelHasWebService), 6);
				createElementLinkMap.Add(typeof(FuentesDeDatosModelHasBaseDatos), 7);
				createElementLinkMap.Add(typeof(FuenteDeDatosPrimariaReferencesBaseDatos), 8);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::VisorDatosDSL.VisorDatosDSLDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new FuentesDeDatosModelHasFuentesDeDatos(partition, roleAssignments, propertyAssignments);
				case 1: return new FuentesDeDatosModelHasFormatosDeSalida(partition, roleAssignments, propertyAssignments);
				case 2: return new FuentesDeDatosModelHasTiposDeChart(partition, roleAssignments, propertyAssignments);
				case 3: return new FuenteDeDatosPrimariaReferencesFormatosDeSalida(partition, roleAssignments, propertyAssignments);
				case 4: return new FuenteDeDatosPrimariaReferencesTiposDeChart(partition, roleAssignments, propertyAssignments);
				case 5: return new FuenteDeDatosPrimariaReferencesWebService(partition, roleAssignments, propertyAssignments);
				case 6: return new FuentesDeDatosModelHasWebService(partition, roleAssignments, propertyAssignments);
				case 7: return new FuentesDeDatosModelHasBaseDatos(partition, roleAssignments, propertyAssignments);
				case 8: return new FuenteDeDatosPrimariaReferencesBaseDatos(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "VisorDatosDSL.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return VisorDatosDSLDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (VisorDatosDSLDomainModel.resourceManager == null)
				{
					VisorDatosDSLDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(VisorDatosDSLDomainModel).Assembly);
				}
				return VisorDatosDSLDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return VisorDatosDSLDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return VisorDatosDSLDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (VisorDatosDSLDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new VisorDatosDSLCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					VisorDatosDSLDomainModel.copyClosure = copyFilter;
				}
				return VisorDatosDSLDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (VisorDatosDSLDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new VisorDatosDSLDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					VisorDatosDSLDomainModel.removeClosure = removeFilter;
				}
				return VisorDatosDSLDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::VisorDatosDSL.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::VisorDatosDSL.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::VisorDatosDSL.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::VisorDatosDSL.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class VisorDatosDSLDeleteClosure : VisorDatosDSLDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public VisorDatosDSLDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class VisorDatosDSLDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public VisorDatosDSLDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::VisorDatosDSL.FuentesDeDatosModelHasFuentesDeDatos.ElementDomainRoleId, true);
			DomainRoles.Add(global::VisorDatosDSL.FuentesDeDatosModelHasFormatosDeSalida.TipoFormatoSalidaWebDomainRoleId, true);
			DomainRoles.Add(global::VisorDatosDSL.FuentesDeDatosModelHasTiposDeChart.TipoDeChartDomainRoleId, true);
			DomainRoles.Add(global::VisorDatosDSL.FuentesDeDatosModelHasWebService.WebServiceDomainRoleId, true);
			DomainRoles.Add(global::VisorDatosDSL.FuentesDeDatosModelHasBaseDatos.BaseDatosDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class VisorDatosDSLCopyClosure : VisorDatosDSLCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public VisorDatosDSLCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class VisorDatosDSLCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public VisorDatosDSLCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

