//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace VisorDatosDSL
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class VisorDatosDSLToolboxHelper : VisorDatosDSLToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new VisorDatosDSLToolboxHelper.
		/// </summary>
		public VisorDatosDSLToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class VisorDatosDSLToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify VisorDatosDSL toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "VisorDatosDSL.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConectorFuente_FormatoSalida connector tool.
		/// </summary>
		public const string ConectorFuente_FormatoSalidaFilterString = "ConectorFuente_FormatoSalida.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Conector_Fuente_TipoChart connector tool.
		/// </summary>
		public const string Conector_Fuente_TipoChartFilterString = "Conector_Fuente_TipoChart.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Conector_Fuente_WebService connector tool.
		/// </summary>
		public const string Conector_Fuente_WebServiceFilterString = "Conector_Fuente_WebService.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConectorFuente_BaseDatos connector tool.
		/// </summary>
		public const string ConectorFuente_BaseDatosFilterString = "ConectorFuente_BaseDatos.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new VisorDatosDSLToolboxHelperBase.
		/// </summary>
		protected VisorDatosDSLToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::VisorDatosDSL.VisorDatosDSLDomainModel.SingletonResourceManager.GetString("VisorDatosDSLToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 9;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::VisorDatosDSL.VisorDatosDSLDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "VisorDatosDSL.FuenteDeDatosToolboxItem":
					// Add FuenteDeDatos shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.FuenteDeDatosToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FuenteDeDatosToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FuenteDeDatosToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FuenteDeDatos", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FuenteDeDatosToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::VisorDatosDSL.FuenteDeDatosPrimaria.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "VisorDatosDSL.FormatoDeSalidaToolboxItem":
					// Add FormatoDeSalida shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.FormatoDeSalidaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FormatoDeSalidaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FormatoDeSalidaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FormatoDeSalida", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FormatoDeSalidaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::VisorDatosDSL.TipoFormatoSalidaWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "VisorDatosDSL.TipoDeChartToolboxItem":
					// Add TipoDeChart shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.TipoDeChartToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TipoDeChartToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TipoDeChartToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TipoDeChart", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TipoDeChartToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::VisorDatosDSL.TipoDeChart.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "VisorDatosDSL.ConectorFuente_FormatoSalidaToolboxItem":

					// Add ConectorFuente_FormatoSalida connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.ConectorFuente_FormatoSalidaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConectorFuente_FormatoSalidaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConectorFuente_FormatoSalidaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConectorFuente_FormatoSalida", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConectorFuente_FormatoSalidaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConectorFuente_FormatoSalidaFilterString)
						});
					break;
				case "VisorDatosDSL.Conector_Fuente_TipoChartToolboxItem":

					// Add Conector_Fuente_TipoChart connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.Conector_Fuente_TipoChartToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Conector_Fuente_TipoChartToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Conector_Fuente_TipoChartToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Conector_Fuente_TipoChart", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Conector_Fuente_TipoChartToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(Conector_Fuente_TipoChartFilterString)
						});
					break;
				case "VisorDatosDSL.WebServiceToolboxItem":
					// Add WebService shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.WebServiceToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("WebServiceToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("WebServiceToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"WebService", // F1 help keyword for the toolbox item.
						resourceManager.GetString("WebServiceToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::VisorDatosDSL.WebService.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "VisorDatosDSL.Conector_Fuente_WebServiceToolboxItem":

					// Add Conector_Fuente_WebService connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.Conector_Fuente_WebServiceToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Conector_Fuente_WebServiceToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Conector_Fuente_WebServiceToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Conector_Fuente_WebService", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Conector_Fuente_WebServiceToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(Conector_Fuente_WebServiceFilterString)
						});
					break;
				case "VisorDatosDSL.BaseDatosToolboxItem":
					// Add BaseDatos shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.BaseDatosToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BaseDatosToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BaseDatosToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"BaseDatos", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BaseDatosToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::VisorDatosDSL.BaseDatos.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "VisorDatosDSL.ConectorFuente_BaseDatosToolboxItem":

					// Add ConectorFuente_BaseDatos connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"VisorDatosDSL.ConectorFuente_BaseDatosToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConectorFuente_BaseDatosToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConectorFuente_BaseDatosToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"VisorDatosDSL.VisorDatosDSLToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VisorDatosDSLToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConectorFuente_BaseDatos", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConectorFuente_BaseDatosToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConectorFuente_BaseDatosFilterString)
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::VisorDatosDSL.VisorDatosDSLDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::VisorDatosDSL.VisorDatosDSLDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
