//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorDatosDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "vdat";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"VisorDatosDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID VisorDatosDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisorDatosDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID VisorDatosDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisorDatosDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewVisorDatosDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisorDatosDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string VisorDatosDSLPackageId = "eac8a017-502c-4d77-a475-4c575dac18a5";
		
		// Editor factory identifier
		public const string VisorDatosDSLEditorFactoryId = "ce997ae5-75a3-4f95-a1b5-012baa76bf66";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string VisorDatosDSLModelExplorerToolWindowId = "bc58c5dc-e214-4505-9636-2b8ed16d30a2";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace VisorDatosDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string VisorDatosDSLCommandSetId = "5a7cd7d1-87d0-4c70-8bfa-07c50c407ca3";
	}
}