//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace VisorDatosDSL
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\14.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(VisorDatosDSLExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(VisorDatosDSLExplorerToolWindow), Constants.VisorDatosDSLEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@VisorDatosDSLToolboxTab;VisorDatosDSL.Dsl.dll", "VisorDatosDSL.VisorDatosDSLToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@FuenteDeDatosToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.FuenteDeDatosToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FuenteDeDatos", 
					"@FuenteDeDatosToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@FormatoDeSalidaToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.FormatoDeSalidaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FormatoDeSalida", 
					"@FormatoDeSalidaToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@TipoDeChartToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.TipoDeChartToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TipoDeChart", 
					"@TipoDeChartToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@ConectorFuente_FormatoSalidaToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.ConectorFuente_FormatoSalidaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorFuente_FormatoSalida", 
					"@ConectorFuente_FormatoSalidaToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@Conector_Fuente_TipoChartToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.Conector_Fuente_TipoChartToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Conector_Fuente_TipoChart", 
					"@Conector_Fuente_TipoChartToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@WebServiceToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.WebServiceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"WebService", 
					"@WebServiceToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@Conector_Fuente_WebServiceToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.Conector_Fuente_WebServiceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Conector_Fuente_WebService", 
					"@Conector_Fuente_WebServiceToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@BaseDatosToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.BaseDatosToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"BaseDatos", 
					"@BaseDatosToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("VisorDatosDSL.VisorDatosDSLToolboxTab",
					"@ConectorFuente_BaseDatosToolboxItem;VisorDatosDSL.Dsl.dll", 
					"VisorDatosDSL.ConectorFuente_BaseDatosToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorFuente_BaseDatos", 
					"@ConectorFuente_BaseDatosToolboxBitmap;VisorDatosDSL.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideEditorFactory(typeof(VisorDatosDSLEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(VisorDatosDSLEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(VisorDatosDSLEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"VisorDatosDSL", typeof(VisorDatosDSLEditorFactory))]

	internal abstract partial class VisorDatosDSLPackageBase : DslShell::ModelingPackage
	{
		protected global::VisorDatosDSL.VisorDatosDSLToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new VisorDatosDSLEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::VisorDatosDSL.VisorDatosDSLToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			VisorDatosDSLCommandSet commandSet = new VisorDatosDSLCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			VisorDatosDSLClipboardCommandSet clipboardCommandSet = new VisorDatosDSLClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(VisorDatosDSLExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace VisorDatosDSL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::VisorDatosDSL.VisorDatosDSLDirectiveProcessor), global::VisorDatosDSL.VisorDatosDSLDirectiveProcessor.VisorDatosDSLDirectiveProcessorName, "A directive processor that provides access to VisorDatosDSL files")]
	[global::System.Runtime.InteropServices.Guid(Constants.VisorDatosDSLPackageId)]
	internal sealed partial class VisorDatosDSLPackage : VisorDatosDSLPackageBase
	{
	}
}